version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_stocks
        description: "Raw stocks data from DuckDB"
        columns:
          - name: Date
            description: "Date of the transaction"
          - name: Ticker
            description: "Ticker symbol of the stock"
          - name: Market
            description: "Market of the stock"
          - name: Open
            description: "Opening price of the stock at the beginning of the day"
          - name: High
            description: "Highest price of the stock during the day"
          - name: Low
            description: "Lowest price of the stock during the day"
          - name: Close
            description: "Closing price of the stock at the end of the day"
          - name: Volume
            description: "Volume of the stock traded during the day"
          - name: Dividends
            description: "Dividends"
          - name: Split
            description: "Splits"
